language: erlang

env:
  - LUAROCKS_BASE=luarocks-2.1.1 LUA=lua5.1 LUA_DEV=liblua5.1-dev LUA_VER=5.1 LUA_SFX=5.1 LUA_INCDIR=/usr/include/lua5.1
  - LUAROCKS_BASE=luarocks-2.1.1 LUA=luajit LUA_DEV=libluajit-5.1-dev LUA_VER=5.1 LUA_SFX=jit LUA_INCDIR=/usr/include/luajit-2.0

before_install:
  - sudo apt-get install $LUA
  - sudo apt-get install $LUA_DEV
  - lua$LUA_SFX -v
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - cd $LUAROCKS_BASE
  - ./configure --lua-version=$LUA_VER --lua-suffix=$LUA_SFX --with-lua-include="$LUA_INCDIR"
  - sudo make install

install:
  - sudo luarocks install busted
  - sudo luarocks install 30log

script: "sudo luarocks make && sudo busted spec"

notifications:
  recipients:
    - matt@ninjapenguin.co.uk
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - gh-pages
