language: erlang

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks libssl1.0.0
  - sudo luarocks install busted
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - sudo luarocks install 30log

script: "sudo luarocks make && sudo busted spec"

notifications:
  recipients:
    - matt@ninjapenguin.co.uk
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - gh-pages
