language: c

env:
  global:
    - LUAROCKS=2.2.0beta1
  matrix:
    - LUA=lua5.2
    - LUA=luajit

before_install:
  - bash .travis/setup_lua.sh
  - sudo luarocks install busted

install:
  - sudo luarocks make

script: "busted spec"

notifications:
  recipients:
    - matt@ninjapenguin.co.uk
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - gh-pages
