language: erlang

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - sudo luarocks install 30log

script: "sudo luarocks make && sudo busted"

notifications:
  recipients:
    - matt@ninjapenguin.co.uk
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - gh-pages
